### ISSUE TITLE
Rebuild more than once a day

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/graphhopper-docker#2]
As a user I world like that the routing database would be updated more than once a day.
Motivation:
I just tried to route though a way I uploaded earlier today to find out the routing database is outdated compared to the map.
I don't think a very complicated mechanism is needed here, but may be just to increase the rebuild to be done 2-3 times a day...

**Comment by zstadler** [comment]
Changed to hourly updates.

**Comment by zstadler** [comment]
Need to switch to openstreetmap.fr and use `pyosmium` to get up-to-date OSM data.

**Comment by HarelM** [comment]
This is using osmbpfwebapi now. closing.
