### ISSUE TITLE
Straight lines sometimes appear when planning a route with no error message

### ISSUE THREAD

**Issue by yargolan** [IsraelHikingMap/graphhopper-docker#3]
## Bug/Feature
(Delete the non-relevant)
תכנון מסלול מתבצע בקווים ישרים בלבד למרות שמסומן לתכנן לרכב שטח
המסלול לא נדבק לסימון השבילים

## What I expect to happen
המסלול אמור להדבק לשביל

## What really happened
כל שתי נקודות מתחברות בקווים ישרים בלבד

## What I did that caused the issue - step by step
פתח את האתר
לחץ על תכנון מסלול
לחץ על רכב שטח
התחל לתכנן מסלול

## My environment
* Operating System and version:
mac 10.15.7

* Web Browser and version:
chrome 89.0.4389.114

**Comment by HarelM** [comment]
I've moved this issue here as I don't see a problem in the site itself.
Graphhopper image was refreshed on the server and we are hoping this would solve the issue.
Nevertheless, we'll keep this open from a few more days to allow people to report back.

**Comment by yargolan** [comment]
Thanks!

It is working fine for me at the moment.

**Comment by HarelM** [comment]
Currently I don't see these errors anymore.
I've added the relevant logging to the site and will be monitoring the logs in the future.
Closing for now...
