### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by tjukanovt** [IsraelHikingMap/graphhopper-docker#4]
Hi! Great work in building a working Docker pipeline for GraphHopper. The repo is missing a license file, so just wanted to check: how is this licensed? MIT?

**Comment by HarelM** [comment]
Actually, the pipeline I setup for docker is here:
https://github.com/IsraelHikingMap/graphhopper-docker-image-push
How did you find this repo.
Not much here to be licensed I guess... What part of it interests you? Maybe I could move it as an example to the other repo...?

**Comment by tjukanovt** [comment]
Found it through Google I guess and I have also seen the other repo. Although there isn't much here, I just thought it is a good and straightforward combination of all the bits an pieces to get GraphHopper up and running and thus wanted to reuse it and make sure that the license allows it.

**Comment by HarelM** [comment]
The elevation part (folder) is a bit more problematic in term of licensing.
But other than that, feel free to use anything here. These are mainly docker files, and simple batch files.
I'll check with my partner regarding the license part.
But I don't see a real problem using what's here for anything you need.

**Comment by tjukanovt** [comment]
Great! Thanks. If it is ok with you, I could delete the elevation zip files and stick a MIT license to my fork?

**Comment by HarelM** [comment]
Sure. Go ahead.

**Comment by HarelM** [comment]
Done, enjoy,
